const app=document.getElementById('app');
const state={screen:'home',vibe:'midnight',type:'photo',title:'',unlockAt:Date.now()+6*86400000+14*3600000+32*60000};
const cd=()=>{let n=Math.max(0,state.unlockAt-Date.now())/1000,d=Math.floor(n/86400),h=Math.floor(n%86400/3600),m=Math.floor(n%3600/60);return `${String(d).padStart(2,'0')} : ${String(h).padStart(2,'0')} : ${String(m).padStart(2,'0')}`};
const nav=a=>`<nav class="bottom-nav"><button class="nav-item ${a==='home'?'active':''}" data-a="home">⌂<small>Home</small></button><button class="nav-add" data-a="create">+</button><button class="nav-item ${a==='profile'?'active':''}" data-a="profile">◉<small>Profile</small></button></nav>`;
const top=t=>`<div class="topbar"><button class="back" data-a="home">‹</button><b class="brand-small">${t}</b><button class="icon-btn" data-a="toast">⚙</button></div>`;
function home(){app.className='screen app-screen';app.innerHTML=`<div class="topbar"><b class="brand-small">LockBox</b><button class="icon-btn" data-a="toast">⚙</button></div><div class="greeting"><div class="avatar">👩🏻</div><div><div class="eyebrow">Good evening,</div><h1 class="h1">Sabah 👋</h1></div></div><section class="feature-card"><div class="feature-lock">🔐</div><div class="feature-label">Your next unlock</div><div class="countdown" id="timer">${cd()}</div><div class="countdown-label">Days &nbsp; Hours &nbsp; Minutes</div><div class="feature-label">Something special is waiting...</div></section><button class="primary-btn create-btn" data-a="create">＋ Create a LockBox <span>→</span></button><div class="section-head"><h2>Your LockBoxes</h2><button data-a="toast">See all</button></div><div class="box-list"><article class="mini-box"><div>💗</div><div><b>Sarah</b><div class="mini-time">Opens in 3 days</div></div></article><article class="mini-box"><div>🌅</div><div><b>Ahmed</b><div class="mini-time">Opens tomorrow</div></div></article><article class="mini-box"><div>🌌</div><div><b>Future Me</b><div class="mini-time">Jan 1, 2027</div></div></article></div>${nav('home')}`}
function create(){app.className='screen app-screen';app.innerHTML=`${top('Create a LockBox')}<div class="eyebrow">Step 1 of 3</div><h1 class="h1" style="font-size:32px">What do you want<br>to lock?</h1><div class="choice-grid"><button class="choice-card" data-a="capture" data-type="message">💬<b>Message</b><span>Write something for later</span></button><button class="choice-card" data-a="capture" data-type="photo">🖼️<b>Photo</b><span>A memory for later</span></button><button class="choice-card" data-a="capture" data-type="voice">🎙️<b>Voice Note</b><span>Say it, don't send it</span></button><button class="choice-card" data-a="capture" data-type="video">🎥<b>Video</b><span>Future you can watch</span></button><button class="choice-card wide" data-a="capture" data-type="mixed">🗂️ <b>Mixed Media</b><span>Add multiple items</span></button></div><p class="hand">Different moments.<br>Same magic. →</p>`}
function capture(){app.className='screen app-screen';let text=state.type==='message';app.innerHTML=`${top('Add your memory')}<div class="capture ${text?'text-capture':''}">${text?'<textarea id="memo" placeholder="Write something for later... ✍️"></textarea>':'<div class="capture-center">'+({photo:'📸',voice:'🎙️',video:'🎥',mixed:'🗂️'}[state.type])+'<small>Tap the button below</small></div>'}</div><button class="primary-btn" data-a="customize">Continue <span>→</span></button>`}
function customize(){app.className='screen app-screen';let vibes=['midnight','dreamy','soft','neon','birthday','spooky','love','nature','minimal'];app.innerHTML=`${top('Customize your LockBox')}<div class="eyebrow">Step 2 of 3</div><h1 class="h1">Make it yours ✨</h1><div class="section-head" style="margin-top:24px"><h2>Choose a vibe</h2></div><div class="theme-grid">${vibes.map(v=>`<button class="theme ${v} ${state.vibe===v?'selected':''}" data-a="vibe" data-v="${v}">${v[0].toUpperCase()+v.slice(1)}</button>`).join('')}</div><div class="field"><label>Add a title (optional)</label><input class="input" id="title" placeholder="A message for later..." value="${state.title}"></div><button class="primary-btn" data-a="unlock">Continue <span>→</span></button>`}
function unlock(){app.className='screen app-screen';app.innerHTML=`${top('When should it unlock?')}<div class="eyebrow">Step 3 of 3</div><h1 class="h1">Choose the moment.</h1><div class="choice-grid"><button class="choice-card wide" data-a="set" data-days="10">📅 <b>Specific Date</b><span>Choose a date & time</span>›</button><button class="choice-card wide" data-a="set" data-days="7">⏱️ <b>Countdown</b><span>e.g. 7 days from now</span>›</button><button class="choice-card wide" data-a="set" data-days="30">🎂 <b>Birthday</b><span>Unlock on their birthday</span>›</button><button class="choice-card wide" data-a="set" data-days="7">👥 <b>Mutual Lock</b><span>Everyone contributes</span>›</button></div>`}
function locked(){app.className='screen app-screen';app.innerHTML=`${top('Your LockBox')}<section class="locked-card"><div class="big-lock">🔐</div><div class="locked-title">LOCKED</div><div class="locked-count" id="locked">${cd()}</div><div class="locked-sub">Days &nbsp; Hours &nbsp; Minutes<br><br>You know you want to look...</div><button class="peek-btn" data-a="peek">👀 Try to Peek</button><div class="nice-try" id="peek"><strong>Nice try. 😈</strong><p>You can't open it yet.</p><button data-a="close">Okay, I'll wait 😅</button></div></section>${nav('home')}`}
function share(){app.className='screen app-screen';app.innerHTML=`${top('Share your LockBox')}<div class="eyebrow">Your LockBox is ready!</div><h1 class="h1">Share it with them 💌</h1><div class="share-preview"><div class="share-lock">🔐</div><h2>Someone locked<br>something for you.</h2><div class="countdown">03 : 12 : 44</div><p>Can you wait? 👀</p></div><div class="share-actions"><button class="share-action" data-a="toast">◎<small>Instagram Story</small></button><button class="share-action" data-a="toast">◉<small>WhatsApp</small></button><button class="share-action" data-a="copy">🔗<small>Copy Link</small></button><button class="share-action" data-a="toast">•••<small>More</small></button></div><button class="primary-btn" data-a="locked">View Locked Box <span>→</span></button>`}
function profile(){app.className='screen app-screen';app.innerHTML=`${top('LockBox')}<section class="profile-head"><div class="avatar">👩🏻</div><div class="profile-name">Sabah</div><div class="eyebrow">Making memories that have to wait.</div><div class="stats"><div class="stat"><strong>12</strong><span>LockBoxes</span></div><div class="stat"><strong>8</strong><span>Unlocked</span></div><div class="stat"><strong>4</strong><span>Waiting</span></div></div></section><div class="tabs"><button class="tab active">My LockBoxes</button><button class="tab">Memories</button></div><div class="history">${[['💗','Sarah','Opens in 3 days'],['🌅','Ahmed','Opens tomorrow'],['🌌','Future Me','Jan 1, 2027']].map(x=>`<div class="history-row"><div class="history-thumb">${x[0]}</div><div class="history-info"><b>${x[1]}</b><span>${x[2]}</span></div><span>›</span></div>`).join('')}</div>${nav('profile')}`}
function render(){({home,create,capture,customize,unlock,locked,share,profile}[state.screen]||home)()}
function toast(){let t=document.querySelector('.toast')||Object.assign(document.createElement('div'),{className:'toast'});t.textContent='Coming soon ✨';document.body.appendChild(t);t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
document.addEventListener('click',e=>{let b=e.target.closest('[data-a]');if(!b)return;let a=b.dataset.a;if(a==='home')state.screen='home';if(a==='create')state.screen='create';if(a==='capture'){state.type=b.dataset.type;state.screen='capture'}if(a==='customize')state.screen='customize';if(a==='vibe'){state.vibe=b.dataset.v}if(a==='unlock'){state.title=document.getElementById('title')?.value||'';state.screen='unlock'}if(a==='set'){state.unlockAt=Date.now()+Number(b.dataset.days)*86400000;state.screen='share'}if(a==='locked')state.screen='locked';if(a==='peek')document.getElementById('peek')?.classList.add('show');if(a==='close')document.getElementById('peek')?.classList.remove('show');if(a==='profile')state.screen='profile';if(a==='copy'){navigator.clipboard?.writeText(location.href);toast()}if(a==='toast')toast();render()});
setInterval(()=>{let x=document.getElementById('timer');if(x)x.textContent=cd();let y=document.getElementById('locked');if(y)y.textContent=cd()},1000);render();
